# /// script
# requires-python = ">=3.12"
# dependencies = ["textual==8.2.8"]
# ///
"""Read-only Textual TUI over the RhubarbTart core API (Phase 0.5, Stage B).

Launched by the ``./rhubarb-tui`` shim. This is a *thin client*: it renders what
the typed core API (``tools/rhubarb/api.py``) returns and never touches ``tart``
or the keychain directly, and never calls any mutating operation
(``new``/``run``/``enroll``/``reset``/``rm``). It is strictly read-only —
``api.images()``, ``api.clones()`` and ``api.provenance(vm)`` only.

Textual is this repo's first third-party Python dependency. It is pinned to an
exact version and hash-verified via uv's script lockfile
(``tools/rhubarb_tui.py.lock``, generated by ``uv lock --script``); the shim runs
this file with ``uv run --script``, which resolves against that lock and verifies
the hashes. See docs/INTERFACE-PLAN.md (decision gate B-0).

The shell owns the layout, keyboard navigation and refresh loop; each pane is a
separate module under ``rhubarb.tui`` (see that package's docstring for the pane
contract). This file mounts the panes and drives their ``refresh_data()``.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from textual.app import App, ComposeResult  # noqa: E402
from textual.binding import Binding  # noqa: E402
from textual.widgets import Footer, Header, TabbedContent, TabPane  # noqa: E402

from rhubarb.tui.clones_pane import ClonesPane  # noqa: E402
from rhubarb.tui.images_pane import ImagesPane  # noqa: E402
from rhubarb.tui.provenance_pane import ProvenancePane  # noqa: E402


class RhubarbTUI(App):
    """A tabbed, keyboard-driven, read-only view of images, clones and provenance."""

    TITLE = "RhubarbTart"
    SUB_TITLE = "control plane · read-only"

    # Seconds between automatic read-only refreshes of every pane.
    REFRESH_INTERVAL = 5.0

    BINDINGS = [
        Binding("q", "quit", "Quit"),
        Binding("r", "refresh_all", "Refresh"),
        Binding("1", "show_tab('images')", "Images"),
        Binding("2", "show_tab('clones')", "Clones"),
        Binding("3", "show_tab('provenance')", "Provenance"),
        # left/right arrows and tab already move between panes via TabbedContent.
    ]

    def compose(self) -> ComposeResult:
        yield Header()
        with TabbedContent(initial="images"):
            with TabPane("Images", id="images"):
                yield ImagesPane(id="images-pane")
            with TabPane("Clones", id="clones"):
                yield ClonesPane(id="clones-pane")
            with TabPane("Provenance", id="provenance"):
                yield ProvenancePane(id="provenance-pane")
        yield Footer()

    def _panes(self):
        """The three pane widgets, in tab order."""
        return (
            self.query_one("#images-pane", ImagesPane),
            self.query_one("#clones-pane", ClonesPane),
            self.query_one("#provenance-pane", ProvenancePane),
        )

    def on_mount(self) -> None:
        self.action_refresh_all()
        self.set_interval(self.REFRESH_INTERVAL, self.action_refresh_all)

    def action_refresh_all(self) -> None:
        """Reload every pane from the core API (read-only)."""
        for pane in self._panes():
            pane.refresh_data()

    def action_show_tab(self, tab: str) -> None:
        self.query_one(TabbedContent).active = tab


def main() -> None:
    RhubarbTUI().run()


if __name__ == "__main__":
    main()
