# /// script
# requires-python = ">=3.12"
# dependencies = ["textual==8.2.8"]
# ///
"""Read-only Textual TUI over the RhubarbTart core API (Phase 0.5, Stage B).

Launched by the ``./rhubarb-tui`` shim. This is a *thin client*: it renders what
the typed core API (``tools/rhubarb/api.py``) returns and never touches ``tart``
or the keychain directly, and never calls any mutating operation
(``new``/``run``/``enroll``/``reset``/``rm``). It is strictly read-only —
``api.images()``, ``api.clones()`` and ``api.provenance(vm)`` only.

Textual is this repo's first third-party Python dependency. It is pinned to an
exact version and hash-verified via uv's script lockfile
(``tools/rhubarb_tui.py.lock``, generated by ``uv lock --script``); the shim runs
this file with ``uv run --script``, which resolves against that lock and verifies
the hashes. See docs/INTERFACE-PLAN.md (decision gate B-0).

The shell owns the layout, keyboard navigation and refresh loop; each pane is a
separate module under ``rhubarb.tui`` (see that package's docstring for the pane
contract). This file mounts the panes and drives their ``refresh_data()``.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from rich.text import Text  # noqa: E402  (bundled with textual)
from textual import work  # noqa: E402
from textual.app import App, ComposeResult  # noqa: E402
from textual.binding import Binding  # noqa: E402
from textual.widgets import DataTable, Footer, Header, RichLog, TabbedContent, TabPane  # noqa: E402

from rhubarb.tui import actions  # noqa: E402
from rhubarb.tui.clones_pane import ClonesPane  # noqa: E402
from rhubarb.tui.confirm import ConfirmScreen  # noqa: E402
from rhubarb.tui.images_pane import ImagesPane  # noqa: E402
from rhubarb.tui.prompt import InputScreen, SelectScreen  # noqa: E402
from rhubarb.tui.provenance_pane import ProvenancePane  # noqa: E402


class RhubarbTUI(App):
    """A tabbed, keyboard-driven view of images, clones and provenance.

    The three panes are strictly read-only (Stage B). Operator *actions* (Stage C)
    are dispatched by the shell — never by the panes — through the action modules in
    ``rhubarb.tui.actions``: each runs in a Textual worker off the UI thread, streams
    its progress into the action log, and destructive actions confirm first via
    ``ConfirmScreen``. ``rm`` is wired end to end; the rest are stubs for the
    per-action agents.
    """

    TITLE = "RhubarbTart"
    SUB_TITLE = "control plane"

    CSS = """
    #action-log {
        height: 8;
        border-top: solid $panel;
        padding: 0 1;
        background: $surface;
    }
    """

    # Seconds between automatic read-only refreshes of every pane.
    REFRESH_INTERVAL = 5.0

    BINDINGS = [
        Binding("q", "quit", "Quit"),
        Binding("r", "refresh_all", "Refresh"),
        Binding("1", "show_tab('images')", "Images"),
        Binding("2", "show_tab('clones')", "Clones"),
        Binding("3", "show_tab('provenance')", "Provenance"),
        # Actions on the highlighted clone (dispatched by the shell, run in a worker;
        # destructive ones confirm first).
        Binding("b", "run_clone", "Run"),
        Binding("s", "ssh_clone", "SSH"),
        Binding("x", "reset_clone", "Reset"),
        Binding("d", "delete_clone", "Remove clone"),
        # Input-driven write actions: they gather a profile/service/name via the
        # prompt modals (rhubarb.tui.prompt) before dispatch. new/build target a
        # profile (not a clone); enroll acts on the highlighted clone.
        Binding("n", "new_clone", "New"),
        Binding("e", "enroll_clone", "Enroll"),
        Binding("B", "build", "Build"),
        # left/right arrows and tab already move between panes via TabbedContent.
    ]

    def compose(self) -> ComposeResult:
        yield Header()
        with TabbedContent(initial="images"):
            with TabPane("Images", id="images"):
                yield ImagesPane(id="images-pane")
            with TabPane("Clones", id="clones"):
                yield ClonesPane(id="clones-pane")
            with TabPane("Provenance", id="provenance"):
                yield ProvenancePane(id="provenance-pane")
        yield RichLog(id="action-log", markup=False, wrap=True, highlight=False)
        yield Footer()

    def _panes(self):
        """The three pane widgets, in tab order."""
        return (
            self.query_one("#images-pane", ImagesPane),
            self.query_one("#clones-pane", ClonesPane),
            self.query_one("#provenance-pane", ProvenancePane),
        )

    def on_mount(self) -> None:
        self.action_refresh_all()
        self.set_interval(self.REFRESH_INTERVAL, self.action_refresh_all)

    def action_refresh_all(self) -> None:
        """Reload every pane from the core API (read-only)."""
        for pane in self._panes():
            pane.refresh_data()

    def action_show_tab(self, tab: str) -> None:
        self.query_one(TabbedContent).active = tab

    # -- action infrastructure (Stage C) --------------------------------------
    # The shell owns action dispatch so the read-only panes stay read-only. The
    # flow: resolve target -> guard -> (confirm if destructive) -> run in a worker,
    # streaming progress into the action log -> apply the outcome (log + refresh).

    def action_delete_clone(self) -> None:
        """Remove the highlighted clone (with confirm)."""
        from rhubarb.tui.actions import rm

        self.dispatch_action(rm)

    def action_run_clone(self) -> None:
        """Start the highlighted clone (GUI window, in the background)."""
        from rhubarb.tui.actions import run

        self.dispatch_action(run, params={"headless": False, "detach": True})

    def action_ssh_clone(self) -> None:
        """SSH into the highlighted clone: the core returns argv, the shell suspends and execs it."""
        from rhubarb.tui.actions import ssh

        self.dispatch_action(ssh)

    def action_reset_clone(self) -> None:
        """Destroy + re-clone the highlighted clone from the current image (with confirm)."""
        from rhubarb.tui.actions import reset

        self.dispatch_action(reset, params={"same_image": False, "rotate": True})

    # -- input-driven write actions (profile/service/name gathered via prompt modals) ----
    # These need operator input before dispatch, so they chain the prompt modals via
    # push_screen callbacks (like ConfirmScreen). Cancelling any modal (Escape) aborts
    # cleanly: log a line, make no api call. The action handlers still validate in the core.

    def _profile_choices(self) -> list[str] | None:
        """The known profile ids for a picker; None (with a log line) when unavailable."""
        try:
            from rhubarb import api

            return sorted(api.list_profiles())
        except Exception as e:  # a missing/broken profiles dir must not crash the app
            self._log_action(f"could not list profiles: {e}", ok=False)
            return None

    def action_new_clone(self) -> None:
        """Create a fresh clone: pick a profile, type a name, then dispatch ``new``."""
        from rhubarb.tui.actions import new

        profiles = self._profile_choices()
        if not profiles:
            if profiles is not None:
                self._log_action(f"{new.LABEL}: no profiles found to build a clone from")
            return

        def got_profile(profile: str | None) -> None:
            if not profile:
                self._log_action(f"{new.LABEL}: cancelled")
                return

            def got_name(name: str | None) -> None:
                if not name:
                    self._log_action(f"{new.LABEL}: cancelled")
                    return
                self.dispatch_action(new, name=name,
                                     params={"profile": profile, "rotate": True})

            self.push_screen(InputScreen(f"New clone name (profile {profile})"), got_name)

        self.push_screen(SelectScreen("Select a profile for the new clone", profiles),
                         got_profile)

    def action_enroll_clone(self) -> None:
        """Enroll the highlighted clone: pick a service (and, for warp, an optional org)."""
        from rhubarb.tui.actions import enroll

        name = self._selected_clone_name()
        if not name:
            self._log_action(f"{enroll.LABEL}: select a clone in the Clones tab first")
            return

        def got_service(service: str | None) -> None:
            if not service:
                self._log_action(f"{enroll.LABEL}: cancelled")
                return
            if service == "warp":
                def got_org(org: str | None) -> None:
                    if org is None:  # Escape aborts
                        self._log_action(f"{enroll.LABEL}: cancelled")
                        return
                    if not org.strip():  # WARP requires a team/org (enroll.sh: "warp needs --org")
                        self._log_action(f"{enroll.LABEL}: WARP needs a team/org name — cancelled",
                                         ok=False)
                        return
                    self.dispatch_action(enroll, name=name,
                                         params={"service": service, "org": org.strip()})

                self.push_screen(
                    InputScreen("Cloudflare WARP team/org (required)"), got_org)
            else:
                self.dispatch_action(enroll, name=name,
                                     params={"service": service, "org": None})

        self.push_screen(
            SelectScreen(f"Enroll {name} in which service?", list(enroll.SERVICES)),
            got_service)

    def action_build(self) -> None:
        """Build a profile image: pick a profile, then dispatch ``build``.

        The build handler streams the GUI-session caveat and refuses over SSH itself,
        so the shell does not duplicate that here.
        """
        from rhubarb.tui.actions import build

        profiles = self._profile_choices()
        if not profiles:
            if profiles is not None:
                self._log_action(f"{build.LABEL}: no profiles found to build")
            return

        def got_profile(profile: str | None) -> None:
            if not profile:
                self._log_action(f"{build.LABEL}: cancelled")
                return
            self.dispatch_action(build, params={"profile": profile})

        self.push_screen(SelectScreen("Build which profile?", profiles), got_profile)

    def on_data_table_row_highlighted(self, event: DataTable.RowHighlighted) -> None:
        """Point the Provenance pane at the highlighted row (read-only).

        Provenance records exist for built images (``out/<image>.provenance.json``), not clones —
        a clone's provenance is that of the image it was cloned from. So an images-table highlight
        shows that image; a clones-table highlight shows the clone's source image.
        """
        try:
            prov = self.query_one("#provenance-pane", ProvenancePane)
        except Exception:
            return
        table_id = event.data_table.id
        if table_id == "images-table":
            try:
                name = str(event.data_table.get_row(event.row_key)[0])
            except Exception:
                return
            prov.show(name)
        elif table_id == "clones-table":
            clone = self._lookup_clone(str(event.row_key.value))
            if clone is not None:
                prov.show(clone.image)

    def dispatch_action(self, module, *, name: str | None = None,
                        clone: object | None = None, params: dict | None = None) -> None:
        """Run an action module for a target, confirming first if it is destructive.

        ``name``/``clone`` default to the highlighted clone in the read-only clones
        table. Applies the ``require_clone`` guard for clone-targeted actions so a
        built image (``rbt-*``) or a ``*-vanilla``/``*-unverified`` precursor is never
        a target — the core enforces this too, this is the friendly UI-side gate.
        """
        if module.REQUIRES_CLONE:
            if name is None:
                name = self._selected_clone_name()
            if not name:
                self._log_action(f"{module.LABEL}: select a clone in the Clones tab first")
                return
            try:
                actions.require_clone(name)
            except actions.NotAClone as e:
                self._log_action(f"refused: {e}", ok=False)
                return
            if clone is None:
                clone = self._lookup_clone(name)

        ctx = actions.ActionContext(name=name or "", clone=clone,
                                    params=params or {}, progress=self._action_progress)

        # DESTRUCTIVE actions (reset/rm) confirm before acting; REQUIRES_ACK actions (build)
        # aren't destructive but must surface an acknowledgement first (the GUI-session caveat).
        if module.DESTRUCTIVE or getattr(module, "REQUIRES_ACK", False):
            def on_confirm(confirmed: bool | None) -> None:
                if confirmed:
                    self._run_action(module, ctx)
                else:
                    self._log_action(f"{module.LABEL}: cancelled")

            self.push_screen(ConfirmScreen(module.confirm_prompt(ctx),
                                           action_label=module.LABEL), on_confirm)
        else:
            self._run_action(module, ctx)

    @work(thread=True, group="rhubarb-action")
    def _run_action(self, module, ctx: "actions.ActionContext") -> None:
        """Run ``module.handle(ctx)`` off the UI thread; report the outcome.

        Runs in a Textual thread worker so the (blocking) core API never freezes the
        UI. All UI updates are marshalled back with ``call_from_thread``.
        """
        try:
            outcome = module.handle(ctx)
        except NotImplementedError as e:
            self.call_from_thread(self._log_action, f"{module.LABEL}: {e}", False)
            return
        except Exception as e:  # a handler bug must not take the app down
            self.call_from_thread(self._log_action,
                                  f"{module.LABEL} FAILED: {type(e).__name__}: {e}", False)
            return
        self.call_from_thread(self._apply_outcome, outcome)

    def _apply_outcome(self, outcome: "actions.ActionOutcome") -> None:
        """Apply an action's result on the UI thread: log it; hand off an interactive
        session if the core returned one; then refresh."""
        self._log_action(outcome.summary, ok=outcome.ok)
        if outcome.exec_argv:
            self._exec_interactive(outcome.exec_argv)
        elif outcome.needs_refresh:
            self.action_refresh_all()

    def _exec_interactive(self, argv: list[str]) -> None:
        """Hand the terminal to an interactive command the core returned as argv (ssh, or a
        foreground run) — the TUI can't host it — then resume the app and refresh. argv is built
        by the core (api.ssh_args / api.run), never from user text."""
        import subprocess

        self._log_action("handing terminal over: " + " ".join(argv))
        with self.suspend():
            subprocess.run(argv)  # noqa: S603
        self.action_refresh_all()

    def _action_progress(self, msg: str) -> None:
        """Progress sink handed to action handlers (and forwarded to the core).

        Called from the worker thread, so it marshals the line onto the UI thread.
        """
        self.call_from_thread(self._log_action, msg)

    def _log_action(self, msg: str, ok: bool | None = None) -> None:
        """Write one line to the action log (UI thread). ``ok`` colours the line."""
        style = "" if ok is None else ("green" if ok else "red bold")
        try:
            self.query_one("#action-log", RichLog).write(Text(msg, style=style))
        except Exception:
            pass

    def _selected_clone_name(self) -> str | None:
        """Read the highlighted clone's name from the read-only clones table.

        Read-only: it only inspects the DataTable cursor; it never mutates the pane.
        """
        try:
            table = self.query_one("#clones-table", DataTable)
            if not table.row_count or not table.is_valid_coordinate(table.cursor_coordinate):
                return None
            return table.coordinate_to_cell_key(table.cursor_coordinate).row_key.value
        except Exception:
            return None

    def _lookup_clone(self, name: str):
        """Find the ``api.Clone`` row for ``name`` (for prompts/messages); best-effort."""
        try:
            from rhubarb import api

            for c in api.clones().clones:
                if c.name == name:
                    return c
        except Exception:
            pass
        return None


def main() -> None:
    RhubarbTUI().run()


if __name__ == "__main__":
    main()
